<?php

namespace App\Landing\Service;

use App\Psiholog\Entity\Psiholog;
use Symfony\Component\Asset\Packages;

class PsihologReview
{
    private const ORIGINAL_REVIEWS = [
        Psiholog::PSIHOLOG_ID_ALISA_CHIZIKOVA => [
            [
                "name" => "Галина",
                "body" => "psiholog_review_alisa_chizikova_1",
                "created" => "2022-02-21",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0001-alice-chizikova/0001.webp?v=j056h45b5",
            ],
            [
                "name" => "Роман Толстопятов",
                "body" => "psiholog_review_alisa_chizikova_2",
                "created" => "2022-02-18",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0001-alice-chizikova/0002.webp?v=j056h45b5",
            ],
            [
                "name" => "Дарина Чёрная",
                "body" => "psiholog_review_alisa_chizikova_3",
                "created" => "2022-01-23",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "sergey semenov",
                "body" => "psiholog_review_alisa_chizikova_4",
                "created" => "2022-01-17",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Serjo",
                "body" => "psiholog_review_alisa_chizikova_5",
                "created" => "2022-01-16",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Златан Ибрагимович",
                "body" => "psiholog_review_alisa_chizikova_6",
                "created" => "2022-01-10",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0001-alice-chizikova/0003.webp?v=j056h45b5",
            ],
            [
                "name" => "Александр Половинко",
                "body" => "psiholog_review_alisa_chizikova_7",
                "created" => "2021-12-25",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0001-alice-chizikova/0004.webp?v=j056h45b5",
            ],
            [
                "name" => "Алина",
                "body" => "psiholog_review_alisa_chizikova_8",
                "created" => "2021-12-06",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "юліана матвійчук",
                "body" => "psiholog_review_alisa_chizikova_9",
                "created" => "2021-11-30",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0001-alice-chizikova/0005.webp?v=j056h45b5",
            ],
            [
                "name" => "Danya Parhomenko",
                "body" => "psiholog_review_alisa_chizikova_10",
                "created" => "2021-11-08",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Andrey Belyaev",
                "body" => "psiholog_review_alisa_chizikova_11",
                "created" => "2021-11-07",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0001-alice-chizikova/0006.webp?v=j056h45b5",
            ],
            [
                "name" => "Артем Литовкин",
                "body" => "psiholog_review_alisa_chizikova_12",
                "created" => "2021-09-30",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Наташа Пуздренко",
                "body" => "psiholog_review_alisa_chizikova_13",
                "created" => "2021-09-30",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Николай Орлов",
                "body" => "psiholog_review_alisa_chizikova_14",
                "created" => "2021-09-10",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0001-alice-chizikova/0007.webp?v=j056h45b5",
            ],
            [
                "name" => "Богдан Оксентюк",
                "body" => "psiholog_review_alisa_chizikova_15",
                "created" => "2021-09-07",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "sugar mommy",
                "body" => "psiholog_review_alisa_chizikova_16",
                "created" => "2021-08-31",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Iren Kab",
                "body" => "psiholog_review_alisa_chizikova_17",
                "created" => "2021-08-28",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Yelyzaveta Okhtinova",
                "body" => "psiholog_review_alisa_chizikova_18",
                "created" => "2021-08-28",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0001-alice-chizikova/0008.webp?v=j056h45b5",
            ],
            [
                "name" => "Sofiya",
                "body" => "psiholog_review_alisa_chizikova_19",
                "created" => "2021-08-28",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0001-alice-chizikova/0009.webp?v=j056h45b5",
            ],
            [
                "name" => "Денис Меженський",
                "body" => "psiholog_review_alisa_chizikova_20",
                "created" => "2021-08-24",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Полина Непран",
                "body" => "psiholog_review_alisa_chizikova_21",
                "created" => "2021-08-21",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Алла Торина",
                "body" => "psiholog_review_alisa_chizikova_22",
                "created" => "2021-08-18",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Диана Глущенко",
                "body" => "psiholog_review_alisa_chizikova_23",
                "created" => "2021-08-17",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Нина Носкова",
                "body" => "psiholog_review_alisa_chizikova_24",
                "created" => "2021-08-17",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0001-alice-chizikova/0010.webp?v=j056h45b5",
            ],
            [
                "name" => "Евгений Краснов",
                "body" => "psiholog_review_alisa_chizikova_25",
                "created" => "2021-07-14",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Александра Мисюра",
                "body" => "psiholog_review_alisa_chizikova_26",
                "created" => "2021-05-21",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Екатерина Жидкова",
                "body" => "psiholog_review_alisa_chizikova_27",
                "created" => "2021-01-26",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Nina Ozimok",
                "body" => "psiholog_review_alisa_chizikova_28",
                "created" => "2020-10-20",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0001-alice-chizikova/0011.webp?v=j056h45b5",
            ],
            [
                "name" => "Аnna Кravchuk",
                "body" => "psiholog_review_alisa_chizikova_29",
                "created" => "2020-10-08",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Timur Alekseev",
                "body" => "psiholog_review_alisa_chizikova_30",
                "created" => "2020-10-03",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Liliya Liliya",
                "body" => "psiholog_review_alisa_chizikova_31",
                "created" => "2020-09-28",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Анна Трунина",
                "body" => "psiholog_review_alisa_chizikova_32",
                "created" => "2020-09-25",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Наталья Гончарова",
                "body" => "psiholog_review_alisa_chizikova_33",
                "created" => "2020-09-22",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Всяко Разно",
                "body" => "psiholog_review_alisa_chizikova_34",
                "created" => "2020-09-22",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Marie Polevara",
                "body" => "psiholog_review_alisa_chizikova_35",
                "created" => "2019-06-27",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0001-alice-chizikova/0012.webp?v=j056h45b5",
            ],
        ],
        Psiholog::PSIHOLOG_ID_ARTEM_KHMELEVSKIY => [
            [
                "name" => "Дарья",
                "body" => "psiholog_review_artem_khmelevskiy_1",
                "created" => "2022-03-17",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Людмила Павлова (коллега)",
                "body" => "psiholog_review_artem_khmelevskiy_2",
                "created" => "2022-01-22",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Anna Nuzha",
                "body" => "psiholog_review_artem_khmelevskiy_3",
                "created" => "2021-10-24",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0010-artem-khmelevskiy/0001.webp?v=j056h45b5",
            ],
            [
                "name" => "Александра Кривенко",
                "body" => "psiholog_review_artem_khmelevskiy_4",
                "created" => "2021-09-07",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0010-artem-khmelevskiy/0003.webp?v=j056h45b5",
            ],
            [
                "name" => "Дмитрий Брыковец",
                "body" => "psiholog_review_artem_khmelevskiy_5",
                "created" => "2021-07-09",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0010-artem-khmelevskiy/0002.webp?v=j056h45b5",
            ],
            [
                "name" => "Ирина Маламура",
                "body" => "psiholog_review_artem_khmelevskiy_6",
                "created" => "2021-05-13",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Илья",
                "body" => "psiholog_review_artem_khmelevskiy_7",
                "created" => "2020-02-03",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Мария",
                "body" => "psiholog_review_artem_khmelevskiy_8",
                "created" => "2019-11-18",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Nero :3",
                "body" => "psiholog_review_artem_khmelevskiy_9",
                "created" => "2019-09-15",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Марина",
                "body" => "psiholog_review_artem_khmelevskiy_10",
                "created" => "2019-07-19",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Green moon",
                "body" => "psiholog_review_artem_khmelevskiy_11",
                "created" => "2019-06-28",
                "is_recommend" => true,
                "rating" => 5,
            ],
        ],
        Psiholog::PSIHOLOG_ID_VIKTORIYA_RADIY => [
            [
                "name" => "Света Воронкова",
                "body" => "psiholog_review_viktoriya_radiy_1",
                "created" => "2021-12-17",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Алина Пилипенко",
                "body" => "psiholog_review_viktoriya_radiy_2",
                "created" => "2021-07-09",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0003-viktoriya-radiy/0002.webp?v=j056h45b5",
            ],
            [
                "name" => "Spizhenko Stanislava",
                "body" => "psiholog_review_viktoriya_radiy_3",
                "created" => "2021-03-27",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Елена Бийчук",
                "body" => "psiholog_review_viktoriya_radiy_4",
                "created" => "2021-01-20",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Диана Райс",
                "body" => "psiholog_review_viktoriya_radiy_5",
                "created" => "2021-01-16",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Bezo Gor",
                "body" => "psiholog_review_viktoriya_radiy_6",
                "created" => "2021-01-09",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0003-viktoriya-radiy/0001.webp?v=j056h45b5",
            ],
        ],
        Psiholog::PSIHOLOG_ID_OKSANA_RYZHIKOVA => [
            [
                'name' => 'Anna Kovalenko',
                'body' => 'psiholog_review_oksana_ryzhikova_1',
                'created' => '2021-08-31',
                'is_recommend' => true,
                'rating' => 5,
                'profileUrl' => 'img/reviews-user-images/0004-oksana-ryzhikova/0001.webp',
            ],
        ],
        Psiholog::PSIHOLOG_ID_INNA_KARASHCHUK => [
            [
                "name" => "Есения Москаленко",
                "body" => "psiholog_review_inna_karaschuk_1",
                "created" => "2022-01-26",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0004.webp?v=j056h45b5",
            ],
            [
                "name" => "Александра Прусикина",
                "body" => "psiholog_review_inna_karaschuk_2",
                "created" => "2021-11-20",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0005.webp?v=j056h45b5",
            ],
            [
                "name" => "Маша Черданцева",
                "body" => "psiholog_review_inna_karaschuk_3",
                "created" => "2021-10-27",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Юля Коваль",
                "body" => "psiholog_review_inna_karaschuk_4",
                "created" => "2021-10-12",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Виктория Авдеева",
                "body" => "psiholog_review_inna_karaschuk_5",
                "created" => "2021-10-01",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Мирослава Иванова",
                "body" => "psiholog_review_inna_karaschuk_6",
                "created" => "2021-09-24",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0006.webp?v=j056h45b5",
            ],
            [
                "name" => "Ольга Янко",
                "body" => "psiholog_review_inna_karaschuk_7",
                "created" => "2021-09-22",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0009.webp?v=j056h45b5",
            ],
            [
                "name" => "Anna Anyshchenko",
                "body" => "psiholog_review_inna_karaschuk_8",
                "created" => "2021-09-22",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0017.webp?v=j056h45b5",
            ],
            [
                "name" => "Марина",
                "body" => "psiholog_review_inna_karaschuk_9",
                "created" => "2021-09-22",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Алина Фролова",
                "body" => "psiholog_review_inna_karaschuk_10",
                "created" => "2021-09-17",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0003.webp?v=j056h45b5",
            ],
            [
                "name" => "Александра Темирова",
                "body" => "psiholog_review_inna_karaschuk_11",
                "created" => "2021-09-14",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0007.webp?v=j056h45b5",
            ],
            [
                "name" => "Liudmyla Skochko",
                "body" => "psiholog_review_inna_karaschuk_12",
                "created" => "2021-09-06",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Lika Dubrova",
                "body" => "psiholog_review_inna_karaschuk_13",
                "created" => "2021-09-01",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Veronica Yalovaya",
                "body" => "psiholog_review_inna_karaschuk_14",
                "created" => "2021-08-31",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0001.webp?v=j056h45b5",
            ],
            [
                "name" => "Oleksandra Khoroshenkova",
                "body" => "psiholog_review_inna_karaschuk_15",
                "created" => "2021-08-25",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Alyona Ishchenko",
                "body" => "psiholog_review_inna_karaschuk_16",
                "created" => "2021-08-23",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0011.webp?v=j056h45b5",
            ],
            [
                "name" => "Татьяна Отрада",
                "body" => "psiholog_review_inna_karaschuk_17",
                "created" => "2021-08-22",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0012.webp?v=j056h45b5",
            ],
            [
                "name" => "Линара Ильгизова",
                "body" => "psiholog_review_inna_karaschuk_18",
                "created" => "2021-08-10",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0002.webp?v=j056h45b5",
            ],
            [
                "name" => "Патрисиа Диас",
                "body" => "psiholog_review_inna_karaschuk_19",
                "created" => "2021-07-16",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Елена Осадчая",
                "body" => "psiholog_review_inna_karaschuk_20",
                "created" => "2021-07-14",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0013.webp?v=j056h45b5",
            ],
            [
                "name" => "Алеся Волощук",
                "body" => "psiholog_review_inna_karaschuk_21",
                "created" => "2021-07-12",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0008.webp?v=j056h45b5",
            ],
            [
                "name" => "Галина Михайлова",
                "body" => "psiholog_review_inna_karaschuk_22",
                "created" => "2021-07-11",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Тамара Т",
                "body" => "psiholog_review_inna_karaschuk_23",
                "created" => "2021-04-07",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Каринка Малинка",
                "body" => "psiholog_review_inna_karaschuk_24",
                "created" => "2021-03-05",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Oleksandr Shapovalov",
                "body" => "psiholog_review_inna_karaschuk_25",
                "created" => "2021-02-24",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0015.webp?v=j056h45b5",
            ],
            [
                "name" => "Olga Dobysheva",
                "body" => "psiholog_review_inna_karaschuk_26",
                "created" => "2021-02-17",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0014.webp?v=j056h45b5",
            ],
            [
                "name" => "Яна Бородакій",
                "body" => "psiholog_review_inna_karaschuk_27",
                "created" => "2021-02-03",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Людмила Сыч",
                "body" => "psiholog_review_inna_karaschuk_28",
                "created" => "2021-01-31",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Марина Бойко",
                "body" => "psiholog_review_inna_karaschuk_29",
                "created" => "2021-01-24",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0010.webp?v=j056h45b5",
            ],
            [
                "name" => "Тетяна Ільєнко",
                "body" => "psiholog_review_inna_karaschuk_30",
                "created" => "2021-01-23",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0016.webp?v=j056h45b5",
            ],
            [
                "name" => "Ирина 777",
                "body" => "psiholog_review_inna_karaschuk_31",
                "created" => "2021-01-23",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Tamila Tamila",
                "body" => "psiholog_review_inna_karaschuk_32",
                "created" => "2021-01-18",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Александра Сорока",
                "body" => "psiholog_review_inna_karaschuk_33",
                "created" => "2021-01-12",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Viktoriia Sydorevych",
                "body" => "psiholog_review_inna_karaschuk_34",
                "created" => "2020-10-23",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0002-inna-karashchuk/0018.webp?v=j056h45b5",
            ],
            [
                "name" => "Катерина Никитина",
                "body" => "psiholog_review_inna_karaschuk_35",
                "created" => "2020-10-18",
                "is_recommend" => true,
                "rating" => 5,
            ],
        ],
        Psiholog::PSIHOLOG_ID_VALENTINA_DOVBYSH => [
            [
                "name" => "Вадим Лещенко",
                "body" => "psiholog_review_valentina_dovbysh_1",
                "created" => "2021-11-17",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Bazi Bazi",
                "body" => "psiholog_review_valentina_dovbysh_2",
                "created" => "2021-11-15",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Mar art",
                "body" => "psiholog_review_valentina_dovbysh_3",
                "created" => "2021-11-03",
                "is_recommend" => true,
                "rating" => 5,
            ],
        ],
        Psiholog::PSIHOLOG_ID_YULIYA_GURNEVICH => [
            [
                "name" => "Viktoria Gladchenko",
                "body" => "psiholog_review_yuliya_gurnevich_1",
                "created" => "2021-09-17",
                "is_recommend" => true,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0001.webp?v=j056h45b5",
                "rating" => 5,
            ],
            [
                "name" => "Alena Dzhemula",
                "body" => "psiholog_review_yuliya_gurnevich_2",
                "created" => "2021-07-26",
                "is_recommend" => true,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0002.webp?v=j056h45b5",
                "rating" => 5,
            ],
            [
                "name" => "Елена Данильченко",
                "body" => "psiholog_review_yuliya_gurnevich_3",
                "created" => "2021-07-25",
                "is_recommend" => true,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0003.webp?v=j056h45b5",
                "rating" => 5,
            ],
            [
                "name" => "Anastasiia Erofeeva",
                "body" => "psiholog_review_yuliya_gurnevich_4",
                "created" => "2021-07-25",
                "is_recommend" => true,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0004.webp?v=j056h45b5",
                "rating" => 5,
            ],
            [
                "name" => "Vitalii Fokin",
                "body" => "psiholog_review_yuliya_gurnevich_5",
                "created" => "2021-07-24",
                "is_recommend" => true,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0005.webp?v=j056h45b5",
                "rating" => 5,
            ],
            [
                "name" => "Anastasiia Mospan",
                "body" => "psiholog_review_yuliya_gurnevich_6",
                "created" => "2021-05-31",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Светлана Леонидовна",
                "body" => "psiholog_review_yuliya_gurnevich_7",
                "created" => "2020-11-20",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Юлия Галаган",
                "body" => "psiholog_review_yuliya_gurnevich_8",
                "created" => "2020-03-24",
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0006.webp?v=j056h45b5",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Валя Чабанова",
                "body" => "psiholog_review_yuliya_gurnevich_9",
                "created" => "2020-01-20",
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0007.webp?v=j056h45b5",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Алина Шаровская",
                "body" => "psiholog_review_yuliya_gurnevich_10",
                "created" => "2020-01-11",
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0008.webp?v=j056h45b5",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Алла Вільчинська",
                "body" => "psiholog_review_yuliya_gurnevich_11",
                "created" => "2019-07-19",
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0009.webp?v=j056h45b5",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Svitlana Shapochka",
                "body" => "psiholog_review_yuliya_gurnevich_12",
                "created" => "2019-02-26",
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0010.webp?v=j056h45b5",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Юлия Чернышева",
                "body" => "psiholog_review_yuliya_gurnevich_13",
                "created" => "2018-04-01",
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0014.webp?v=j056h45b5",
                "is_recommend" => true,
                "rating" => 4,
            ],
            [
                "name" => "Олександр Сніжко",
                "body" => "psiholog_review_yuliya_gurnevich_14",
                "created" => "2017-02-02",
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0011.webp?v=j056h45b5",
                "is_recommend" => true,
                "rating" => 4,
            ],
            [
                "name" => "Андрей Ко",
                "body" => "psiholog_review_yuliya_gurnevich_15",
                "created" => "2016-09-21",
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0012.webp?v=j056h45b5",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Марина Антоневич",
                "body" => "psiholog_review_yuliya_gurnevich_16",
                "created" => "2016-09-07",
                "profileUrl" => "/assets/landing/img/reviews-user-images/0006-yuliya-gurnevich/0013.webp?v=j056h45b5",
                "is_recommend" => true,
                "rating" => 5,
            ],
        ],
        Psiholog::PSIHOLOG_ID_NATALYA_PONOMAREVA =>  [
            [
                "name" => "Денис Лаврищев",
                "body" => "psiholog_review_natalya_ponomareva_1",
                "created" => "2021-01-24",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0012-natalya-ponomareva/0001.webp?v=j056h45b5"
            ],
            [
                "name" => "Viktoria Lukyanets",
                "body" => "psiholog_review_natalya_ponomareva_2",
                "created" => "2020-10-18",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0012-natalya-ponomareva/0002.webp?v=j056h45b5"
            ],
            [
                "name" => "Мария Пахоменко",
                "body" => "psiholog_review_natalya_ponomareva_3",
                "created" => "2020-10-19",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0012-natalya-ponomareva/0003.webp?v=j056h45b5"
            ],
            [
                "name" => "Дина Кукузеева",
                "body" => "psiholog_review_natalya_ponomareva_4",
                "created" => "2020-10-25",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0012-natalya-ponomareva/0004.webp?v=j056h45b5"
            ],
            [
                "name" => "Алена Масюк",
                "body" => "psiholog_review_natalya_ponomareva_5",
                "created" => "2019-06-30",
                "is_recommend" => true,
                "rating" => 5
            ],
            [
                "name" => "Алла Ткаченко",
                "body" => "psiholog_review_natalya_ponomareva_6",
                "created" => "2020-10-13",
                "is_recommend" => true,
                "rating" => 5
            ],
            [
                "name" => "Elena",
                "body" => "psiholog_review_natalya_ponomareva_7",
                "created" => "2020-09-29",
                "is_recommend" => true,
                "rating" => 5,
                "profileUrl" => "/assets/landing/img/reviews-user-images/0012-natalya-ponomareva/0005.webp?v=j056h45b5"
            ],
            [
                "name" => "Евгения Каплунова",
                "body" => "psiholog_review_natalya_ponomareva_8",
                "created" => "2020-09-30",
                "is_recommend" => true,
                "rating" => 5
            ]
        ],
        Psiholog::PSIHOLOG_ID_NADEZHDA_TORDIYA => [
            [
                "name" => "Диана",
                "body" => "psiholog_review_nadezhda_tordiya_1",
                "created" => "2022-06-14",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Елена",
                "body" => "psiholog_review_nadezhda_tordiya_2",
                "created" => "2022-06-14",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Михаил",
                "body" => "psiholog_review_nadezhda_tordiya_3",
                "created" => "2022-06-14",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Елена",
                "body" => "psiholog_review_nadezhda_tordiya_4",
                "created" => "2022-06-14",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Виктория",
                "body" => "psiholog_review_nadezhda_tordiya_5",
                "created" => "2022-06-14",
                "is_recommend" => true,
                "rating" => 4,
            ],
            [
                "name" => "Маргарита",
                "body" => "psiholog_review_nadezhda_tordiya_6",
                "created" => "2022-06-14",
                "is_recommend" => true,
                "rating" => 4,
            ],
            [
                "name" => "Inna",
                "body" => "psiholog_review_nadezhda_tordiya_7",
                "created" => "2022-06-14",
                "is_recommend" => true,
                "rating" => 4,
            ],
            [
                "name" => "Жанна",
                "body" => "psiholog_review_nadezhda_tordiya_8",
                "created" => "2021-11-23",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Вика",
                "body" => "psiholog_review_nadezhda_tordiya_9",
                "created" => "2021-05-28",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Валентина",
                "body" => "psiholog_review_nadezhda_tordiya_10",
                "created" => "2021-05-18",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Александр",
                "body" => "psiholog_review_nadezhda_tordiya_11",
                "created" => "2021-04-23",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Эка",
                "body" => "psiholog_review_nadezhda_tordiya_12",
                "created" => "2021-01-10",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Арина",
                "body" => "psiholog_review_nadezhda_tordiya_13",
                "created" => "2020-11-02",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Софья",
                "body" => "psiholog_review_nadezhda_tordiya_14",
                "created" => "2020-10-26",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Станислава",
                "body" => "psiholog_review_nadezhda_tordiya_15",
                "created" => "2020-10-11",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Ольга",
                "body" => "psiholog_review_nadezhda_tordiya_16",
                "created" => "2020-10-01",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Юлия",
                "body" => "psiholog_review_nadezhda_tordiya_17",
                "created" => "2020-07-14",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Марьям",
                "body" => "psiholog_review_nadezhda_tordiya_18",
                "created" => "2020-07-05",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Наталья",
                "body" => "psiholog_review_nadezhda_tordiya_19",
                "created" => "2020-07-01",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Александр",
                "body" => "psiholog_review_nadezhda_tordiya_20",
                "created" => "2020-06-24",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Юлия",
                "body" => "psiholog_review_nadezhda_tordiya_21",
                "created" => "2020-06-16",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Ольга",
                "body" => "psiholog_review_nadezhda_tordiya_22",
                "created" => "2020-05-30",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Антон",
                "body" => "psiholog_review_nadezhda_tordiya_23",
                "created" => "2020-05-27",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Елена",
                "body" => "psiholog_review_nadezhda_tordiya_24",
                "created" => "2020-05-07",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Ольга",
                "body" => "psiholog_review_nadezhda_tordiya_25",
                "created" => "2020-05-04",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Евгения",
                "body" => "psiholog_review_nadezhda_tordiya_26",
                "created" => "2020-04-21",
                "is_recommend" => true,
                "rating" => 5,
            ],
            [
                "name" => "Татьяна",
                "body" => "psiholog_review_nadezhda_tordiya_27",
                "created" => "2020-01-10",
                "is_recommend" => false,
                "rating" => 3,
            ],
        ],
    ];

    private const PACKAGE_NAME = 'landing';
    private ?array $reviews = null;

    public function __construct(
        private Packages $packages
    ) {
    }

    public function get(int $psihologId): array
    {
        if (!isset($this->reviews[$psihologId])) {
            $this->initReviews($psihologId);
        }

        return $this->reviews[$psihologId];
    }

    private function initReviews(int $psihologId): void
    {
        $originalReviews = self::ORIGINAL_REVIEWS[$psihologId] ?? [];
        if (!empty($originalReviews)) {
            foreach ($originalReviews as $key => $review) {
                if (isset($review['profileUrl'])) {
                    $review['profileUrl'] = $this->packages->getUrl($review['profileUrl'], self::PACKAGE_NAME);
                    $originalReviews[$key] = $review;
                }
            }
        }

        $this->reviews[$psihologId] = $originalReviews;
    }
}
